[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerfileTarget = "api"

[deploy]
startCommand = "/bin/bash /app/start_api.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
