[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.dockerfile]
target = "api"

[deploy]
startCommand = "sh -c 'exec /bin/bash /app/start_api.sh'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
